### ISSUE TITLE
run error in stage 5 -----empty graph

### ISSUE THREAD

**Issue by curlneuron** [YiwenShaoStephen/pychain_example#11]
Hi，
when i use the mini_librispeech in run.sh : Stage 5
Here is a problem.

Initializing dataset...
100%|███████████████████████████████████████████████████████████████████████████| 1519/1519 [00:01<00:00, 1170.80it/s]
Initializing dataset...
  0%|                                                                                        | 0/1089 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "../../train.py", line 330, in <module>
    main()
  File "../../train.py", line 126, in main
    validset = ChainDataset(args.valid, no_feat=args.no_feat)
  File "pychain_example/dataset.py", line 145, in __init__
    graph = ChainGraph(fst, log_domain=True)
  File "pychain/graph.py", line 70, in __init__
    raise Exception("An empty graph encountered!")
Exception: An empty graph encountered!

**Comment by curlneuron** [comment]
If I just comment out the exception line(line #70) in graph.py, will there be any problem in the following stages?

**Comment by YiwenShaoStephen** [comment]
Yes. You can simply comment out that exception as I've already skipped empty graphs in dataset.py.

**Comment by curlneuron** [comment]
Thank u very much.
But then it comes out another problem when I use a larger dataset at the processing of "Initializing dataset..."

484.21it/s]
  9%|██████▉                                                                  | 52105/548596 [35:12<16:03, 515.20it/s]
 10%|██████▉                                                                  | 52158/548596 [35:12<16:02, 515.77it/s]
 10%|██████▉                                                                  | 52218/548596 [35:12<15:28, 534.64it/s]
 10%|██████▉                                                                  | 52273/548596 [35:12<16:18, 507.24it/s]Traceback (most recent call last):
  File "../../train.py", line 330, in <module>
    main()
  File "../../train.py", line 121, in main
    trainset = ChainDataset(args.train, no_feat=args.no_feat)
  File "pychain_example/dataset.py", line 144, in __init__
    fst = simplefst.StdVectorFst.read_ark(filename, offset)
TypeError: read_ark(): incompatible function arguments. The following argument types are supported:
    1. (arg0: str, arg1: int) -> simplefst.StdVectorFst

Invoked with: 'pychain/mini_librispeech/data/graph/monophone/train/num.1.ark', 2147491251

**Comment by curlneuron** [comment]
And I'm very confused that if the types are wrong, why this error is not at the beginning but is at 10%'s data initializing?

**Comment by curlneuron** [comment]
run it again, and it's all ok.

**Comment by groadabike** [comment]
> If I just comment out the exception line(line #70) in graph.py, will there be any problem in the following stages?

Thank you, I was struggling with this part.
